services:
  database:
    container_name: "local-database-postgres"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - "../.env.development"
    ports:
      - "5432:5432"
  email:
    container_name: "local-email-mailcatcher"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
