name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      # uses: "usa" uma action jรก existente
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts-hydrogen"
      # run: "roda" um comando diretamente na instancia da maquina do job
      - run: npm ci
      - run: npm test
